services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    develop:
      watch:
        - action: rebuild
          path: ./backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - taskapp
    restart: on-failure

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    secrets:
      - db-password
    environment:
      SA_PASSWORD: /run/secrets/db-password
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - taskapp

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - api
      - sqlserver
    environment:
      - VITE_API_URL=http://localhost:8080
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    networks:
      - taskapp

networks:
  taskapp:

volumes:
  sqlvolume:

secrets:
  db-password:
    file: db/password.txt
